insert into alien values(101,'Abhijit', 'C++')
insert into alien values(102,'Navin', 'Java')
insert into alien values(103,'Kiran', 'Android')
insert into alien values(104,'Pravin', 'Python')
insert into alien values(105,'Komal', 'Java')
insert into alien values(106,'Rafiq', 'Android')